# LeanCloud cloud engine automatically wakes up
name: AutoWakeUpLeanCLoud

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule: 
    - cron: "*/18 0-15 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest   
    if: github.event.repository.owner.id == github.event.sender.id  # When you click Star to the warehouse, trigger the Github Action to run
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python  
      uses: actions/setup-python@v1
      with:
        python-version: 3.8  
    - name: Install requests 
      run: |
        pip install requests
    - name: Waking  
      env: 
        $CONFIG_SITE: ${{ secrets.Site }} 
      run: | 
        python run.py ${{ secrets.Site }}
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Commit 
      run: |
        git config --global user.email AutoWakeUp@email.com
        git config --global user.name AutoWakeUp
        git add .
        git commit -m "Successfully Wake" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
