name: 'LeanCloud Self Wake'

 # Triggering conditions
on:
  push:
  watch:
    types: [started]
  schedule:
    - cron: '*/29 23-23 * * ?'    # 7:00-7:59 Beijing time, triggered every 29 minutes
    - cron: '*/29 0-15 * * ?'     # Beijing time 8:00-23:59, triggered every 29 minutes

jobs:
  curl-my-site:
     runs-on: ubuntu-latest
     steps:
       - name: 'xecute command'
         env:
           MY_SITE: ${{ secrets.SITE }}
         # Send a GET request to the site
         run: |                                   
           curl $MY_SITE
